### ISSUE TITLE
Setup Github actions for code formatting and quality

### ISSUE THREAD

**Issue by kvantricht** [Open-EO/openeo-gfmap#16]
Inspiration from [`presto-worldcereal`](https://github.com/WorldCereal/presto-worldcereal/blob/main/.github/workflows/ci.yaml)

**Comment by soxofaan** [comment]
Already did initial setup based on presto-worldcereal inspiration

- [x] basic github actions setup
- [ ] enable + fix isort checks -> #21 
- [ ] enable + fix black checks -> #22 
- [ ] enable + fix flake8
- [ ] enable + fix pytest collection checks  -> #23
